speedEnchantment:
  expCost: 30
  multiplier: 2
  slot: 11
  name: "&b&LSpeed Enchant"
  lore:
    - "&8(&7*&8) &7Gives you permanent speed!"
    - ""
    - "&7» &b&lENCHANTMENT TYPE &7Boots"
    - "&7» &b&lENCHANTMENT COST &7%cost% Levels"
strengthEnchantment:
  expCost: 30
  multiplier: 1
  slot: 12
  name: "&b&LStrength Enchant"
  lore:
    - "&8(&7*&8) &7Gives you permanent strength!"
    - ""
    - "&7» &b&lENCHANTMENT TYPE &7Chestplate"
    - "&7» &b&lENCHANTMENT COST &7%cost% Levels"
fireResistEnchantment:
  expCost: 30
  multiplier: 1
  slot: 13
  name: "&b&LFireResistance Enchant"
  lore:
    - "&8(&7*&8) &7Gives you permanent fire resistance!"
    - ""
    - "&7» &b&lENCHANTMENT TYPE &7Leggings"
    - "&7» &b&lENCHANTMENT COST &7%cost% Levels"
waterBreathingEnchantment:
  expCost: 30
  multiplier: 1
  slot: 14
  name: "&b&LWaterBreathing Enchant"
  lore:
    - "&8(&7*&8) &7Gives you permanent water breathing!"
    - ""
    - "&7» &b&lENCHANTMENT TYPE &7Helmet"
    - "&7» &b&lENCHANTMENT COST &7%cost% Levels"
nightVisionEnchantment:
  expCost: 30
  multiplier: 1
  slot: 15
  name: "&b&LNightVision Enchant"
  lore:
    - "&8(&7*&8) &7Gives you permanent night vision!"
    - ""
    - "&7» &b&lENCHANTMENT TYPE &7Helmet"
    - "&7» &b&lENCHANTMENT COST &7%cost% Levels"
jumpBoostEnchantment:
  expCost: 30
  multiplier: 1
  slot: 21
  name: "&b&LJumpBoost Enchant"
  lore:
    - "&8(&7*&8) &7Give you permanent jump boost!"
    - ""
    - "&7» &b&lENCHANTMENT TYPE &7Boots"
    - "&7» &b&lENCHANTMENT COST &7%cost% Levels"
implantsEnchantment:
  expCost: 30
  multiplier: 1
  slot: 22
  name: "&b&LImplants Enchant"
  lore:
    - "&8(&7*&8) &7Never lose hunger!"
    - ""
    - "&7» &b&lENCHANTMENT TYPE &7Helmet"
    - "&7» &b&lENCHANTMENT COST &7%cost% Levels"
obsidianBreakerEnchantment:
  expCost: 30
  multiplier: 1
  slot: 23
  name: "&b&LObsidianBreaker Enchantment"
  lore:
    - "&8(&7*&8) &7Instantly breaks obsidian!"
    - ""
    - "&7» &b&lENCHANTMENT TYPE &7Pickaxe"
    - "&7» &b&lENCHANTMENT COST &7%cost% Levels"
inventorySize: 36
inventoryName: "&c&lEnchanter"
fillInventory: true
enchantSuccessful: "&a&lEnchant successful!"
# IGNORE (DO NOT TOUCH)
blocked:
  - FURNACE
  - CHEST
  - TRAPPED_CHEST
  - BEACON
  - DISPENSER
  - DROPPER
  - HOPPER
  - WORKBENCH
  - ENCHANTMENT_TABLE
  - ENDER_CHEST
  - ANVIL
  - BED_BLOCK
  - FENCE_GATE
  - SPRUCE_FENCE_GATE
  - BIRCH_FENCE_GATE
  - ACACIA_FENCE_GATE
  - JUNGLE_FENCE_GATE
  - DARK_OAK_FENCE_GATE
  - IRON_DOOR_BLOCK
  - WOODEN_DOOR
  - SPRUCE_DOOR
  - BIRCH_DOOR
  - JUNGLE_DOOR
  - ACACIA_DOOR
  - DARK_OAK_DOOR
  - WOOD_BUTTON
  - STONE_BUTTON
  - TRAP_DOOR
  - IRON_TRAPDOOR
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - FENCE
  - SPRUCE_FENCE
  - BIRCH_FENCE
  - JUNGLE_FENCE
  - DARK_OAK_FENCE
  - ACACIA_FENCE
  - NETHER_FENCE
  - BREWING_STAND
  - CAULDRON
  - LEGACY_SIGN_POST
  - LEGACY_WALL_SIGN
  - LEGACY_SIGN
  - ACACIA_SIGN
  - ACACIA_WALL_SIGN
  - BIRCH_SIGN
  - BIRCH_WALL_SIGN
  - DARK_OAK_SIGN
  - DARK_OAK_WALL_SIGN
  - JUNGLE_SIGN
  - JUNGLE_WALL_SIGN
  - OAK_SIGN
  - OAK_WALL_SIGN
  - SPRUCE_SIGN
  - SPRUCE_WALL_SIGN
  - LEVER
  - BLACK_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - LIME_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - PINK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - RED_SHULKER_BOX
  - SILVER_SHULKER_BOX
  - WHITE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - DAYLIGHT_DETECTOR_INVERTED
  - DAYLIGHT_DETECTOR
  - BARREL
  - BLAST_FURNACE
  - SMOKER
  - CARTOGRAPHY_TABLE
  - COMPOSTER
  - GRINDSTONE
  - LECTERN
  - LOOM
  - STONECUTTER
  - BELL